### ISSUE TITLE
curl extension compatibility support

### ISSUE THREAD

**Issue by eezhal92** [Xfers/xfers-php#1]
Hi.

I try to install this package but it complain my ext curl.

`xfers/xfers-php v1.1.0 requires ext-curl ^0.0.0 -> the requested PHP extension curl has the wrong version (7.0.12-1+deb.sury.org~trusty+1) installed.`

Maybe `composer.json` should be updated?

Thanks

**Comment by hanif** [comment]
pull request submitted #2
